Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/For:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before
Naming/MethodParameterName:
  Enabled: false
